version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGES_USER: borel
      POSTGES_PASSWORD: pass04
      POSTGES_DB: orina

  redis:
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
